[package]
name = "math_calculator"
version = "0.1.0"
edition = "2024"
description = "a lib with math expr ast build and exec"
license = "MIT"

[dependencies]
thiserror = "2.0.12"
lazy_static = "1.4.0"
